<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Gallery;
use Illuminate\Support\Facades\DB;

class GallerySeeder extends Seeder
{
    public function run(): void
    {
        $galleryData = [
            [
                'gallery_id' => 1,
                'title' => 'Sunset Dreams',
                'description' => 'A vibrant sunset landscape with dreamy colors and soft brush strokes.',
                'image_url' => 'https://i.pinimg.com/474x/11/25/be/1125be932e61f84607089e1daa3ba496.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 150000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 2,
                'title' => 'Urban Jungle',
                'description' => 'Modern cityscape with nature elements blending in.',
                'image_url' => 'https://i.pinimg.com/736x/8a/fd/d8/8afdd88e6bc2e9eabd9a4f639d463c31.jpg',
                'file_format' => 'AI',
                'status' => 'sold',
                'price' => 200000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 10:31:03',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 3,
                'title' => 'Ocean Waves',
                'description' => 'Serene ocean scene with gentle waves and peaceful atmosphere.',
                'image_url' => 'https://i.pinimg.com/736x/06/b7/2c/06b72cd4cbbfb9996d27334d48e50b70.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 120000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 4,
                'title' => 'Midnight Garden',
                'description' => 'Mystical garden scene under moonlight with glowing flowers.',
                'image_url' => 'https://i.pinimg.com/1200x/20/79/25/2079253ad6c3d70f2c03c95cbd5d074a.jpg',
                'file_format' => 'PSD',
                'status' => 'sold',
                'price' => 180000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 5,
                'title' => 'Cherry Blossom',
                'description' => 'Beautiful cherry blossom tree in full bloom.',
                'image_url' => 'https://i.pinimg.com/736x/84/8f/a2/848fa2788592253bcb01f395e1f3427f.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 135000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 6,
                'title' => 'Starry Night Sky',
                'description' => 'Breathtaking night sky filled with stars and nebula.',
                'image_url' => 'https://i.pinimg.com/1200x/74/38/a0/7438a018e6ef535bb9f7b218501b4ff2.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 175000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 7,
                'title' => 'Mountain Peak',
                'description' => 'Majestic mountain landscape with snow-capped peaks.',
                'image_url' => 'https://i.pinimg.com/1200x/d6/d9/ec/d6d9ec5e1bc6ca379a4b65b99217ce13.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 160000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 8,
                'title' => 'Autumn Forest',
                'description' => 'Golden autumn forest with warm colors and falling leaves.',
                'image_url' => 'https://i.pinimg.com/1200x/36/54/fb/3654fbe841f5fdd5641b03ad0d60f766.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 140000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 9,
                'title' => 'Cosmic Galaxy',
                'description' => 'Abstract cosmic art with swirling galaxies and vibrant colors.',
                'image_url' => 'https://i.pinimg.com/736x/67/5b/83/675b834da236fc20c70e13a13f40fc23.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 190000.00,
                'created_at' => '2025-10-31 02:56:53',
                'updated_at' => '2025-10-31 02:56:53',
                'deleted_at' => null,
            ],
            [
                'gallery_id' => 10,
                'title' => 'Desert Dunes',
                'description' => 'Peaceful desert landscape with rolling sand dunes.',
                'image_url' => 'https://i.pinimg.com/736x/ca/93/22/ca93223c53c6ca8cf5b658bdc2d98fa8.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 145000.00,
            ],
            [
                'gallery_id' => 11,
                'title' => 'Crystal Lake',
                'description' => 'A calm lake reflecting the surrounding mountains and sky.',
                'image_url' => 'https://i.pinimg.com/736x/a8/4c/24/a84c24bffdc5b73df02a8ef78df21d89.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 155000.00,
            ],
            [
                'gallery_id' => 12,
                'title' => 'Northern Lights',
                'description' => 'Aurora borealis dancing across the night sky.',
                'image_url' => 'https://i.pinimg.com/736x/fc/9e/13/fc9e13ef5cc2f4a0efdbf25a6401d7ef.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 210000.00,
            ],
            [
                'gallery_id' => 13,
                'title' => 'Mystic River',
                'description' => 'A fantasy-style river scene with glowing waters.',
                'image_url' => 'https://i.pinimg.com/736x/62/5a/99/625a998dcad5a28fbc62b4475480c1c3.jpg',
                'file_format' => 'AI',
                'status' => 'sold',
                'price' => 195000.00,
            ],
            [
                'gallery_id' => 14,
                'title' => 'Rainy Window',
                'description' => 'Raindrops trickling down a window with blurred lights outside.',
                'image_url' => 'https://i.pinimg.com/736x/3d/f0/ea/3df0eabddf5987dd8f1db28d75df5428.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 125000.00,
            ],
            [
                'gallery_id' => 15,
                'title' => 'Pastel Clouds',
                'description' => 'Soft pastel-colored clouds with dreamy atmosphere.',
                'image_url' => 'https://i.pinimg.com/736x/df/da/20/dfda20c6c2fd2b463e7faab1fd1e72c1.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 130000.00,
            ],
            [
                'gallery_id' => 16,
                'title' => 'Neon City',
                'description' => 'Cyberpunk-inspired city at night with neon lights.',
                'image_url' => 'https://i.pinimg.com/736x/1b/f4/f6/1bf4f6d9366e86edc2697b0e5f43e05c.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 220000.00,
            ],
            [
                'gallery_id' => 17,
                'title' => 'Forest Path',
                'description' => 'A calm forest trail with sunlight filtering through trees.',
                'image_url' => 'https://i.pinimg.com/736x/4b/64/1c/4b641c24e557c0b04d9fdbf7d0f31cf7.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 140000.00,
            ],
            [
                'gallery_id' => 18,
                'title' => 'Galaxy Portal',
                'description' => 'Sci-fi inspired glowing galaxy portal in outer space.',
                'image_url' => 'https://i.pinimg.com/736x/6a/63/48/6a6348a48b040c5933b536c1c667b2d9.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 250000.00,
            ],
            [
                'gallery_id' => 19,
                'title' => 'Vintage Street',
                'description' => 'Old town street view with warm nostalgic tones.',
                'image_url' => 'https://i.pinimg.com/736x/e7/41/df/e741df47d6826e76d14d39bfe44dc09e.jpg',
                'file_format' => 'PSD',
                'status' => 'sold',
                'price' => 180000.00,
            ],
            [
                'gallery_id' => 20,
                'title' => 'Blooming Meadow',
                'description' => 'A bright meadow full of colorful flowers and sunlight.',
                'image_url' => 'https://i.pinimg.com/736x/2a/5c/91/2a5c91a8d7cc2cf3aeb0e2d06d3a3c3d.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 145000.00,
            ],
            [
                'gallery_id' => 21,
                'title' => 'Fantasy Castle',
                'description' => 'A grand fantasy castle floating in the clouds.',
                'image_url' => 'https://i.pinimg.com/736x/93/a1/fb/93a1fb7eb35f39ff24cb8fd92e3f0b74.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 200000.00,
            ],
            [
                'gallery_id' => 22,
                'title' => 'Golden Hour',
                'description' => 'Landscape bathed in warm golden sunlight before dusk.',
                'image_url' => 'https://i.pinimg.com/736x/ce/69/9d/ce699d02d5d4b19d54a2a76d20af47ab.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 160000.00,
            ],
            [
                'gallery_id' => 23,
                'title' => 'Cyber Horizon',
                'description' => 'Futuristic digital horizon with glowing grids and sun.',
                'image_url' => 'https://i.pinimg.com/736x/40/aa/65/40aa65dc5107a28bb8b89c08d99db7b8.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 210000.00,
            ],
            [
                'gallery_id' => 24,
                'title' => 'Mirror Lake',
                'description' => 'Perfect reflection of mountains on still lake waters.',
                'image_url' => 'https://i.pinimg.com/736x/08/d7/53/08d7536c8e907da4c1c8ed343b04f224.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 170000.00,
            ],
            [
                'gallery_id' => 25,
                'title' => 'Winter Cabin',
                'description' => 'Snowy cabin in a forest with smoke rising from chimney.',
                'image_url' => 'https://i.pinimg.com/736x/b3/3a/5c/b33a5c40e4827062b9c6c8c1d759e995.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 150000.00,
            ],
            [
                'gallery_id' => 26,
                'title' => 'Galaxy Bloom',
                'description' => 'A surreal art of a flower blooming into a galaxy.',
                'image_url' => 'https://i.pinimg.com/736x/56/3e/d8/563ed8e5fa8df6cc4b1acfa8e3b3cf4b.jpg',
                'file_format' => 'AI',
                'status' => 'sold',
                'price' => 240000.00,
            ],
            [
                'gallery_id' => 27,
                'title' => 'Café Morning',
                'description' => 'Warm cozy café morning scene with sunlight.',
                'image_url' => 'https://i.pinimg.com/736x/8d/ab/4f/8dab4f6eb32b55c58b784a3519f09bb9.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 135000.00,
            ],
            [
                'gallery_id' => 28,
                'title' => 'Celestial Path',
                'description' => 'Path of light leading through stars and constellations.',
                'image_url' => 'https://i.pinimg.com/736x/b2/2f/8c/b22f8c25f41ff07df4f0de6c20c5e17a.jpg',
                'file_format' => 'AI',
                'status' => 'available',
                'price' => 260000.00,
            ],
            [
                'gallery_id' => 29,
                'title' => 'Mystery Forest',
                'description' => 'Foggy enchanted forest with glowing light orbs.',
                'image_url' => 'https://i.pinimg.com/736x/0c/d9/d5/0cd9d56f6c61d476a2f28b2fcd0a42cf.jpg',
                'file_format' => 'PSD',
                'status' => 'available',
                'price' => 185000.00,
            ],
            [
                'gallery_id' => 30,
                'title' => 'Dreamscape',
                'description' => 'Abstract surreal dreamscape with floating islands and glowing light.',
                'image_url' => 'https://i.pinimg.com/736x/5f/8a/3c/5f8a3c9e24bb59b3b72c2c6bcd4d26e1.jpg',
                'file_format' => 'PNG',
                'status' => 'available',
                'price' => 230000.00,
            ],
        ];

        foreach ($galleryData as $gallery) {
            DB::table('gallery')->insert(array_merge($gallery, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ GallerySeeder: Dummy gallery data inserted successfully!');
    }
}

